# OrbisAgent Service Wrapper
# This script runs the agent bootstrap which downloads and runs the latest agent
# Generated by OrbisAgent MSI Installer

$ErrorActionPreference = 'Continue'

# Load configuration
$configPath = Join-Path $PSScriptRoot "config.json"
if (Test-Path $configPath) {
    $config = Get-Content $configPath | ConvertFrom-Json
    $CoreServiceUrl = $config.coreServiceUrl
} else {
    $CoreServiceUrl = "http://127.0.0.1:5000"
}

# Change to agent directory
Set-Location -Path $PSScriptRoot

# Run the bootstrap which will download and run the latest agent
Write-Host "Starting OrbisAgent Bootstrap..." -ForegroundColor Cyan
Write-Host "  Core Service: $CoreServiceUrl" -ForegroundColor White
Write-Host ""

& ".\OrbisAgent-Bootstrap.ps1" -CoreServiceUrl $CoreServiceUrl
